"""
SmartPay Guard - Model Training and Evaluation Pipeline
=======================================================
This script trains a Random Forest Classifier to detect fraudulent transactions.

Beginner-Friendly Explanation:
1. We load the transaction dataset generated by generate_data.py.
2. We clean and prepare the data (Preprocessing):
   - Standardize numerical values (e.g. amount, distance).
   - One-hot encode categories (e.g. transaction type, channel).
3. We split the data into 80% for Training (learning patterns) and 20% for Testing (verifying accuracy).
4. We train a Random Forest model (an ensemble of decision trees voting together).
5. We calculate evaluation metrics:
   - Accuracy: Overall percentage of correct predictions.
   - Precision: Out of all transactions flagged as fraud, how many were actually fraud?
   - Recall: Out of all actual fraud transactions, how many did we successfully catch?
   - F1-Score: Harmonic balance between Precision and Recall.
6. We save the trained pipeline to 'models/fraud_model.joblib' so the Streamlit web app can use it instantly.
"""

import os
import json
import joblib
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

import sys

# Ensure project root is in Python's search path
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

def train_and_evaluate_model():
    data_path = os.path.join(PROJECT_ROOT, "data", "transactions.csv")
    model_dir = os.path.join(PROJECT_ROOT, "models")
    os.makedirs(model_dir, exist_ok=True)
    
    # 1. Load Data (If not present, generate it)
    if not os.path.exists(data_path):
        print("Data file not found. Auto-generating synthetic transaction dataset...")
        from data.generate_data import save_dataset
        save_dataset(data_path)
        
    print(f"Loading transaction dataset from {data_path}...")
    df = pd.read_csv(data_path)
    print(f"Dataset loaded: {df.shape[0]} rows, {df.shape[1]} columns")
    
    # 2. Define Features and Target
    feature_cols = [
        'amount',
        'transaction_type',
        'channel',
        'time_of_day_hour',
        'account_age_days',
        'daily_transaction_count',
        'failed_login_attempts',
        'distance_from_home_km',
        'is_foreign_transaction'
    ]
    
    numerical_cols = [
        'amount',
        'time_of_day_hour',
        'account_age_days',
        'daily_transaction_count',
        'failed_login_attempts',
        'distance_from_home_km'
    ]
    
    categorical_cols = [
        'transaction_type',
        'channel',
        'is_foreign_transaction'
    ]
    
    X = df[feature_cols]
    y = df['is_fraud']
    
    # 3. Train/Test Split (80% Train, 20% Test)
    # stratify=y ensures the percentage of fraud is identical in both train and test sets
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=42, stratify=y
    )
    print(f"Training set: {len(X_train)} samples | Testing set: {len(X_test)} samples")
    
    # 4. Build Preprocessing Transformers
    # - Numerical features: Scaled to have mean 0 and variance 1
    # - Categorical features: One-hot encoded into binary columns
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', StandardScaler(), numerical_cols),
            ('cat', OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False), categorical_cols)
        ]
    )
    
    # 5. Build Random Forest Classifier
    # class_weight='balanced' gives more weight to the minority fraud class
    rf_classifier = RandomForestClassifier(
        n_estimators=120,
        max_depth=12,
        min_samples_split=5,
        min_samples_leaf=2,
        class_weight='balanced',
        random_state=42,
        n_jobs=-1
    )
    
    # Create complete end-to-end Pipeline
    pipeline = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('classifier', rf_classifier)
    ])
    
    # 6. Train Model
    print("\nTraining Random Forest model...")
    pipeline.fit(X_train, y_train)
    print("Model training complete!")
    
    # 7. Model Evaluation on Test Set
    y_pred = pipeline.predict(X_test)
    y_proba = pipeline.predict_proba(X_test)[:, 1]
    
    acc = float(accuracy_score(y_test, y_pred))
    prec = float(precision_score(y_test, y_pred))
    rec = float(recall_score(y_test, y_pred))
    f1 = float(f1_score(y_test, y_pred))
    auc = float(roc_auc_score(y_test, y_proba))
    cm = confusion_matrix(y_test, y_pred).tolist()
    
    print("\n" + "=" * 55)
    print("       MODEL EVALUATION RESULTS (TEST DATASET)")
    print("=" * 55)
    print(f"Accuracy  : {acc * 100:.2f}%  -> (Total correct predictions)")
    print(f"Precision : {prec * 100:.2f}%  -> (How many predicted frauds are truly fraud)")
    print(f"Recall    : {rec * 100:.2f}%  -> (How many actual frauds were caught)")
    print(f"F1-Score  : {f1 * 100:.2f}%  -> (Balanced score between Precision & Recall)")
    print(f"ROC-AUC   : {auc * 100:.2f}%  -> (Separation ability between classes)")
    print("\nConfusion Matrix:")
    print(f"  True Negatives  (Normal correctly approved)   : {cm[0][0]}")
    print(f"  False Positives (Normal falsely flagged)      : {cm[0][1]}")
    print(f"  False Negatives (Fraud missed / slipped by)   : {cm[1][0]}")
    print(f"  True Positives  (Fraud correctly caught)      : {cm[1][1]}")
    print("=" * 55)
    
    # 8. Extract Feature Importance
    # Get encoded feature names
    cat_encoder = pipeline.named_steps['preprocessor'].named_transformers_['cat']
    cat_feature_names = cat_encoder.get_feature_names_out(categorical_cols).tolist()
    all_feature_names = numerical_cols + cat_feature_names
    
    importances = pipeline.named_steps['classifier'].feature_importances_.tolist()
    feature_importance_dict = [
        {"feature": name, "importance": round(imp * 100, 2)}
        for name, imp in sorted(zip(all_feature_names, importances), key=lambda x: x[1], reverse=True)
    ]
    
    # 9. Save Model and Metrics
    model_output_path = os.path.join(model_dir, "fraud_model.joblib")
    metrics_output_path = os.path.join(model_dir, "model_metrics.json")
    
    joblib.dump(pipeline, model_output_path)
    print(f"\nModel pipeline saved to: {model_output_path}")
    
    metrics_data = {
        "accuracy": round(acc, 4),
        "precision": round(prec, 4),
        "recall": round(rec, 4),
        "f1_score": round(f1, 4),
        "roc_auc": round(auc, 4),
        "confusion_matrix": cm,
        "feature_importances": feature_importance_dict,
        "features": feature_cols,
        "numerical_cols": numerical_cols,
        "categorical_cols": categorical_cols
    }
    
    with open(metrics_output_path, "w") as f:
        json.dump(metrics_data, f, indent=4)
        
    print(f"Model evaluation metrics saved to: {metrics_output_path}")
    print("Ready for Streamlit web application!")

if __name__ == "__main__":
    train_and_evaluate_model()
